'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {getSupabaseClient} from '@/lib/supabase'
import type {Reservation} from '@/lib/types'

export default function ReservationsPage(){
  const [rows,setRows]=useState<Reservation[]>([]);const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const [filter,setFilter]=useState<'all'|'confirmed'|'cancelled'>('all')
  useEffect(()=>{void load()},[])
  async function load(){const sb=getSupabaseClient();if(!sb){setLoading(false);return}const {data:{user}}=await sb.auth.getUser();if(!user){setMsg('ログインすると予約履歴を確認できます。');setLoading(false);return}const {data,error}=await sb.from('reservations').select('*,hotels(name,slug,image_url,area,city,address,google_maps_url,google_place_id)').eq('user_id',user.id).order('created_at',{ascending:false});if(error)setMsg(error.message);else setRows((data||[]) as Reservation[]);setLoading(false)}
  async function cancel(id:string){const sb=getSupabaseClient();if(!sb)return;if(!confirm('この予約をキャンセルしますか？コインは返金されます。'))return;setMsg('キャンセル処理中...');const {error}=await sb.rpc('cancel_reservation',{p_reservation_id:id});if(error)setMsg(error.message);else{setMsg('キャンセルしました。コインを返金しました。');await load()}}
  const visible=useMemo(()=>filter==='all'?rows:rows.filter(r=>r.status===filter),[rows,filter])
  const confirmed=rows.filter(r=>r.status==='confirmed')
  return <main>
    <section className="pageHero reservationsHero"><div className="eyebrow">MY TRIPS</div><h1>予約・旅程</h1><p>チェックインからホテルまで、次の旅に必要な情報をここに。</p><div className="tripSummary"><div><b>{confirmed.length}</b><span>予約中</span></div><div><b>{rows.length}</b><span>すべて</span></div><div><b>{confirmed.reduce((s,r)=>s+r.coin_amount,0).toLocaleString()}</b><span>利用coin</span></div></div></section>
    <section className="section reservationsSection"><div className="tripTabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>すべて</button><button className={filter==='confirmed'?'active':''} onClick={()=>setFilter('confirmed')}>予約中</button><button className={filter==='cancelled'?'active':''} onClick={()=>setFilter('cancelled')}>キャンセル</button></div>
      {loading?<div className="pageLoading">読み込み中...</div>:visible.length?<div className="reservationList premiumReservationList">{visible.map(r=>{const destination=encodeURIComponent(`${r.hotels?.name||''} ${r.hotels?.address||r.hotels?.city||''}`);return <article className={'reservationCard premiumReservationCard '+r.status} key={r.id}><div className="reservationVisual"><div className="reservationVisualTop"><span className={'status '+r.status}>{r.status==='confirmed'?'予約確定':'キャンセル済み'}</span><span>{r.hotels?.city||'TripNest'}</span></div><small>CONFIRMATION</small><b>{r.confirmation_code||'---'}</b></div><div className="reservationBody"><div className="reservationDate"><div><small>CHECK IN</small><b>{r.check_in}</b></div><span>→</span><div><small>CHECK OUT</small><b>{r.check_out}</b></div></div><h3>{r.hotels?.name||'TripNest Hotel'}</h3><p>{r.total_nights}泊 ・ {r.guests}名{r.hotels?.address?` ・ ${r.hotels.address}`:''}</p><div className="reservationPrice"><span>利用コイン</span><strong>● {r.coin_amount.toLocaleString()} coin</strong></div><div className="reservationActions three">{r.hotels?.slug&&<Link href={`/hotels/${r.hotels.slug}`}>ホテル詳細</Link>}{r.status==='confirmed'&&<a href={`https://www.google.com/maps/dir/?api=1&destination=${destination}${r.hotels?.google_place_id?`&destination_place_id=${encodeURIComponent(r.hotels.google_place_id)}`:''}`} target="_blank" rel="noreferrer">経路を見る</a>}{r.status==='confirmed'&&<button onClick={()=>cancel(r.id)}>キャンセル</button>}</div></div></article>})}</div>:<div className="empty modernEmpty"><div className="emptyIcon">✦</div><b>{filter==='all'?'予約はまだありません':'該当する予約はありません'}</b><span>実在ホテルから、次の旅を見つけてみましょう。</span><Link className="primaryLink" href="/">ホテルを探す</Link></div>}{msg&&<div className="message centerMessage toastMessage">{msg}</div>}</section>
  </main>
}
